import Navbar from '@/component/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter,Roboto } from 'next/font/google'
import Footer from '@/component/Footer/Footer';

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
